# Generated by Django 4.1.7 on 2024-01-22 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TankCo2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('co2', models.CharField(max_length=5)),
            ],
            options={
                'verbose_name_plural': 'co2',
            },
        ),
        migrations.CreateModel(
            name='TankFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filter', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TankHardscape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hardscape', models.CharField(max_length=100)),
                ('hardscape_type', models.CharField(choices=[('S', 'Stone'), ('W', 'Wood')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='TankLight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('light', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TankSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='TankSoil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soil', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TankVolume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Tank volume',
            },
        ),
    ]
